apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: nodejs.appmeshworkshop.hosted.local
  namespace: appmesh-workshop-ns
spec:
  meshName: appmesh-workshop
  virtualRouter:
    listeners:
      - portMapping:
          port: 3000
          protocol: http
  routes:
    - name: route-to-nodejs-app
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: nodejs-appmeshworkshop-hosted-local
              weight: 1