apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-nodejs
  annotations:
    external-dns.alpha.kubernetes.io/hostname: foo.bar.baz
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  selector:
    app: 'ecsdemo-nodejs'
  ports:
  -  protocol: 'TCP'
     port: 3000
     targetPort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '5'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '2'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 3000}]'
    kubernetes.io/ingress.class: alb
    note: This is appmesh workshop
  labels:
    app: alb-ingress-rules
    variant: appmeshworkshop
  name: alb-ingress-rules
  namespace: default
spec:
  rules:
  - host: nodejs.appmeshworkshop.hosted.local
    http:
      paths:
      - path: /*
        backend:
          serviceName: ecsdemo-nodejs
          servicePort: 3000

